name: Build & publish docker image "elrond-sdk-localnet"

on:
  workflow_dispatch:
    inputs:
      DockerTag:
        description: "Docker Tag"
        required: true
        default: "latest"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./elrond-sdk-erdpy-localnet.dockerfile
          tags: elrondnetwork/elrond-sdk-erdpy-localnet:latest,elrondnetwork/elrond-sdk-erdpy-localnet:${{ github.event.inputs.DockerTag }}