name: Build & publish frozen image

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Frozen image (with tag)
        options: 
        - elrond-sdk-erdpy-rust:frozen-001
        - elrond-sdk-erdpy-rust:frozen-002
        
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      # https://stackoverflow.com/questions/32113330/check-if-imagetag-combination-already-exists-on-docker-hub
      - name: Ensure image isn't already published
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect elrondnetwork/${{ github.event.inputs.image }} >/dev/null; then
              echo "Frozen image already published. Will NOT publish."
              exit 1
          else
              echo "Frozen image not yet published. Will publish."
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./${{ github.event.inputs.image }}.dockerfile
          tags: elrondnetwork/${{ github.event.inputs.image }}
